{{- if .Values.cloudTunnel.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "espwifi.io.fullname" . }}-cloudtunnel
  labels:
    {{- include "espwifi.io.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudtunnel
spec:
  type: {{ .Values.cloudTunnel.service.type }}
  ports:
    - port: {{ .Values.cloudTunnel.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "espwifi.io.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cloudtunnel
{{- end }}


