import os
import sys
from pathlib import Path

try:
    Import("env")  # type: ignore  # noqa: F821
except Exception:
    env = None  # Running outside PlatformIO


def generate_sdkconfig(env_name: str, project_dir: Path) -> bool:
    """Combine common + environment defaults into sdkconfig.defaults."""
    configs_dir = project_dir / "configs"
    common_src = configs_dir / "sdkconfig.common.defaults"
    env_src = configs_dir / f"sdkconfig.{env_name}.defaults"
    sources = [src for src in (common_src, env_src) if src.exists()]

    if not sources:
        print(
            f"[sdkconfig] No defaults found for env '{env_name}'. Expected: {env_src}"
        )
        return False

    header = [
        "# Auto-generated by set_sdkconfig.py; edit configs/*.defaults instead.",
        f"# Environment: {env_name}",
        "",
    ]

    chunks = []
    for src in sources:
        chunks.append(f"# --- Begin {src.name} ---")
        chunks.append(src.read_text(encoding="utf-8").rstrip())
        chunks.append(f"# --- End {src.name} ---")
        chunks.append("")  # spacer

    content = "\n".join(header + chunks).rstrip() + "\n"
    dst = project_dir / "sdkconfig.defaults"

    if dst.exists() and dst.read_text(encoding="utf-8") == content:
        print(f"[sdkconfig] {dst} already up to date for env '{env_name}'")
        return False

    dst.write_text(content, encoding="utf-8")
    print("[sdkconfig] Wrote", dst, "from", ", ".join(str(s) for s in sources))
    return True


def _pre_action(
    source, target, env
):  # PlatformIO/SCons passes (target, source, env)
    generate_sdkconfig(env["PIOENV"], Path(env["PROJECT_DIR"]))


if env is not None:
    env.AddPreAction("buildprog", _pre_action)


if __name__ == "__main__":
    env_name = (
        sys.argv[1] if len(sys.argv) > 1 else os.environ.get("PIOENV", "esp32")
    )
    project_dir = Path(os.environ.get("PROJECT_DIR", Path.cwd()))
    generate_sdkconfig(env_name, project_dir)
