// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: ESPWiFi

#ifndef _ESPWIFI_UI_H
#define _ESPWIFI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_MainScreen.h"
#include "screens/ui_BluetoothScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_bluetooth_1_png);   // assets/bluetooth_1.png
LV_IMG_DECLARE( ui_img_play_png);   // assets/play.png
LV_IMG_DECLARE( ui_img_home_png);   // assets/home.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
