// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Background[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_Background[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Primary[2] = {0x47FFF0, 0x47FFF0};
const ui_theme_variable_t _ui_theme_alpha_Primary[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Error[2] = {0xFE4245, 0xFE4245};
const ui_theme_variable_t _ui_theme_alpha_Error[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_ESPWIFI;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

