// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: ESPWiFi

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Background[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_Background[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Primary[2] = {0xF3127C, 0xF3127C};
const ui_theme_variable_t _ui_theme_alpha_Primary[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Error[2] = {0xE20044, 0xE20044};
const ui_theme_variable_t _ui_theme_alpha_Error[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Text[2] = {0xFFFFFF, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_Text[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Secondary[2] = {0x333333, 0x333333};
const ui_theme_variable_t _ui_theme_alpha_Secondary[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_ESPWIFI;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

