// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: ESPWiFi

#include "../ui.h"

void ui_event_comp_HomeButton_HomeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
lv_obj_t **comp_HomeButton = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
}
}

// COMPONENT HomeButton

lv_obj_t *ui_HomeButton_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_HomeButton;
cui_HomeButton = lv_imagebutton_create(comp_parent);
lv_imagebutton_set_src(cui_HomeButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
lv_obj_set_width( cui_HomeButton, 48);
lv_obj_set_height( cui_HomeButton, 48);
lv_obj_set_x( cui_HomeButton, -81 );
lv_obj_set_y( cui_HomeButton, 120 );
lv_obj_set_align( cui_HomeButton, LV_ALIGN_CENTER );

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_HOMEBUTTON_NUM);
children[UI_COMP_HOMEBUTTON_HOMEBUTTON] = cui_HomeButton;
lv_obj_add_event_cb(cui_HomeButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_HomeButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_HomeButton, ui_event_comp_HomeButton_HomeButton, LV_EVENT_ALL, children);
ui_comp_HomeButton_create_hook(cui_HomeButton);
return cui_HomeButton; 
}

