// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: ESPWiFi

#include "../ui.h"

// COMPONENT InfoLabel

lv_obj_t *ui_InfoLabel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_InfoLabel;
cui_InfoLabel = lv_label_create(comp_parent);
lv_obj_set_width( cui_InfoLabel, 198);
lv_obj_set_height( cui_InfoLabel, 193);
lv_obj_set_align( cui_InfoLabel, LV_ALIGN_CENTER );
lv_label_set_text(cui_InfoLabel,"");
lv_obj_add_flag( cui_InfoLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_WITH_ARROW );   /// Flags
lv_obj_remove_flag( cui_InfoLabel, LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
ui_object_set_themeable_style_property(cui_InfoLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text);
ui_object_set_themeable_style_property(cui_InfoLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text);
lv_obj_set_style_text_align(cui_InfoLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_INFOLABEL_NUM);
children[UI_COMP_INFOLABEL_INFOLABEL] = cui_InfoLabel;
lv_obj_add_event_cb(cui_InfoLabel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_InfoLabel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_InfoLabel_create_hook(cui_InfoLabel);
return cui_InfoLabel; 
}

