// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: ESPWiFi

#ifndef _UI_COMP_HOMEBUTTON_H
#define _UI_COMP_HOMEBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT HomeButton
#define UI_COMP_HOMEBUTTON_HOMEBUTTON 0
#define _UI_COMP_HOMEBUTTON_NUM 1
lv_obj_t *ui_HomeButton_create(lv_obj_t *comp_parent);
void ui_event_comp_HomeButton_HomeButton( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
