// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_Button1_create_hook( lv_obj_t * comp)
{
}

void ui_comp_HomeButton_create_hook( lv_obj_t * comp)
{
}

void ui_comp_InfoLabel_create_hook( lv_obj_t * comp)
{
}
