// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: ESPWiFi

#include "../ui.h"

lv_obj_t *ui_BluetoothScreen = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_HomeButton1 = NULL;lv_obj_t *ui_BluetoothButton = NULL;lv_obj_t *ui_BluetoothInfoLabel = NULL;lv_obj_t *ui_BluetoothDropdown = NULL;
// event funtions

// build funtions

void ui_BluetoothScreen_screen_init(void)
{
ui_BluetoothScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_BluetoothScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_BluetoothScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_BluetoothScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_Label4 = lv_label_create(ui_BluetoothScreen);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 0 );
lv_obj_set_y( ui_Label4, -123 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Bluetooth");
ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Primary);
ui_object_set_themeable_style_property(ui_Label4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Primary);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeButton1 = ui_HomeButton_create(ui_BluetoothScreen);
lv_obj_set_x( ui_HomeButton1, -81 );
lv_obj_set_y( ui_HomeButton1, 120 );

ui_BluetoothButton = lv_imagebutton_create(ui_BluetoothScreen);
lv_imagebutton_set_src(ui_BluetoothButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_bluetooth_1_png, NULL);
lv_obj_set_width( ui_BluetoothButton, 48);
lv_obj_set_height( ui_BluetoothButton, 48);
lv_obj_set_x( ui_BluetoothButton, 80 );
lv_obj_set_y( ui_BluetoothButton, 122 );
lv_obj_set_align( ui_BluetoothButton, LV_ALIGN_CENTER );

ui_BluetoothInfoLabel = ui_InfoLabel_create(ui_BluetoothScreen);
lv_obj_set_width( ui_BluetoothInfoLabel, 198);
lv_obj_set_height( ui_BluetoothInfoLabel, 61);
lv_obj_set_x( ui_BluetoothInfoLabel, 0 );
lv_obj_set_y( ui_BluetoothInfoLabel, -62 );
lv_label_set_text(ui_BluetoothInfoLabel,"Click BT Button to Scan for Devices");

ui_BluetoothDropdown = lv_dropdown_create(ui_BluetoothScreen);
lv_dropdown_set_text( ui_BluetoothDropdown, "Devices");
lv_obj_set_width( ui_BluetoothDropdown, 150);
lv_obj_set_height( ui_BluetoothDropdown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BluetoothDropdown, 0 );
lv_obj_set_y( ui_BluetoothDropdown, 2 );
lv_obj_set_align( ui_BluetoothDropdown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_BluetoothDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
ui_object_set_themeable_style_property(ui_BluetoothDropdown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Text);
ui_object_set_themeable_style_property(ui_BluetoothDropdown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Text);
ui_object_set_themeable_style_property(ui_BluetoothDropdown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Secondary);
ui_object_set_themeable_style_property(ui_BluetoothDropdown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Secondary);
ui_object_set_themeable_style_property(ui_BluetoothDropdown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_BluetoothDropdown, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Background);

ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_BluetoothDropdown),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Secondary);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_BluetoothDropdown),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Secondary);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_BluetoothDropdown),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_BluetoothDropdown),  LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Background);

ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_BluetoothDropdown),  LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Primary);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_BluetoothDropdown),  LV_PART_SELECTED| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Primary);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_BluetoothDropdown),  LV_PART_SELECTED| LV_STATE_CHECKED, LV_STYLE_BG_COLOR, _ui_theme_color_Primary);
ui_object_set_themeable_style_property(lv_dropdown_get_list(ui_BluetoothDropdown),  LV_PART_SELECTED| LV_STATE_CHECKED, LV_STYLE_BG_OPA, _ui_theme_alpha_Primary);

}

void ui_BluetoothScreen_screen_destroy(void)
{
   if (ui_BluetoothScreen) lv_obj_del(ui_BluetoothScreen);

// NULL screen variables
ui_BluetoothScreen= NULL;
ui_Label4= NULL;
ui_HomeButton1= NULL;
ui_BluetoothButton= NULL;
ui_BluetoothInfoLabel= NULL;
ui_BluetoothDropdown= NULL;

}
