// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: ESPWiFi

#ifndef UI_BLUETOOTHSCREEN_H
#define UI_BLUETOOTHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BluetoothScreen
extern void ui_BluetoothScreen_screen_init(void);
extern void ui_BluetoothScreen_screen_destroy(void);
extern lv_obj_t *ui_BluetoothScreen;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_HomeButton1;
extern lv_obj_t *ui_BluetoothButton;
extern lv_obj_t *ui_BluetoothInfoLabel;
extern lv_obj_t *ui_BluetoothDropdown;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

