// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: ESPWiFi

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_Label1;
extern void ui_event_BluetoothSettingsButton( lv_event_t * e);
extern lv_obj_t *ui_BluetoothSettingsButton;
extern lv_obj_t *ui_PlayButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

