// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Calendar1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Calendar1 = lv_calendar_create(ui_Screen1);
lv_obj_t *ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
lv_obj_set_width( ui_Calendar1, 230);
lv_obj_set_height( ui_Calendar1, 240);
lv_obj_set_align( ui_Calendar1, LV_ALIGN_CENTER );

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Calendar1= NULL;

}
