// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_SettingsScreen = NULL;lv_obj_t *ui_HomeButton = NULL;lv_obj_t *ui_WiFiButton = NULL;lv_obj_t *ui_BluetoothButton = NULL;
// event funtions
void ui_event_HomeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_MainScreen_screen_init);
}
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
ui_SettingsScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SettingsScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_SettingsScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_HomeButton = lv_imagebutton_create(ui_SettingsScreen);
lv_imagebutton_set_src(ui_HomeButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
lv_obj_set_width( ui_HomeButton, 48);
lv_obj_set_height( ui_HomeButton, 48);
lv_obj_set_align( ui_HomeButton, LV_ALIGN_CENTER );

ui_WiFiButton = lv_imagebutton_create(ui_SettingsScreen);
lv_imagebutton_set_src(ui_WiFiButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_wifi_off_png, NULL);
lv_imagebutton_set_src(ui_WiFiButton, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_wifi_on_png, NULL);
lv_imagebutton_set_src(ui_WiFiButton, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_wifi_on_png, NULL);
lv_obj_set_width( ui_WiFiButton, 48);
lv_obj_set_height( ui_WiFiButton, 48);
lv_obj_set_x( ui_WiFiButton, -54 );
lv_obj_set_y( ui_WiFiButton, 114 );
lv_obj_set_align( ui_WiFiButton, LV_ALIGN_CENTER );

ui_BluetoothButton = lv_imagebutton_create(ui_SettingsScreen);
lv_imagebutton_set_src(ui_BluetoothButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_bluetooth_1_png, NULL);
lv_obj_set_width( ui_BluetoothButton, 48);
lv_obj_set_height( ui_BluetoothButton, 50);
lv_obj_set_x( ui_BluetoothButton, 54 );
lv_obj_set_y( ui_BluetoothButton, 114 );
lv_obj_set_align( ui_BluetoothButton, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_HomeButton, ui_event_HomeButton, LV_EVENT_ALL, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
   if (ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

// NULL screen variables
ui_SettingsScreen= NULL;
ui_HomeButton= NULL;
ui_WiFiButton= NULL;
ui_BluetoothButton= NULL;

}
