// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_WIFISETTINGSSCREEN_H
#define UI_WIFISETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WiFiSettingsScreen
extern void ui_WiFiSettingsScreen_screen_init(void);
extern void ui_WiFiSettingsScreen_screen_destroy(void);
extern lv_obj_t *ui_WiFiSettingsScreen;
extern lv_obj_t *ui_Label2;
extern void ui_event_HomeButton( lv_event_t * e);
extern lv_obj_t *ui_HomeButton;
extern lv_obj_t *ui_WiFiButton;
extern lv_obj_t *ui_WiFiInfoLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

